landscape.yml

added TCN Twitter

---

landscape.yml

T. E. new projects

---

README.md

Updating Readme with some more instructions specific to LFPH.

Add info on flags to logos section

---

hosted_logos/herald.svg
landscape.yml

* [x ] Is your app/project/product currently shipping and/or have the source code available?
* [ n/a] If an app, does your homepage include links to download the Android and/or iOS apps?
* [ x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [TBD ] Have you picked the single best (existing) category for your project?
* [ x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ x] Does your logo clearly state the name of the …

Add Herald

---

settings.yml

te-Express

---

landscape.yml

Move covid watch

---

landscape.yml

Move Washington to express

---

landscape.yml

This commit is in honor and memory of Dan Kohn:
- founder of Linux Foundation Public Health
- the storyteller and visionary of the landscape app
- a deeply missed mentor who empowered so many
Thank you Dan for being a part of New Zealand`s Open Source Story.
I know you'd be proud to see this become reality.
🇳🇿
See: https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-resources-and-tools/nz-covid-tracer-app/open-source-release-nz-covid-tracer

New Zealand Open Sources COVID Tracer App w/ Bluetooth+AGPL

---

landscape.yml

add more repos to india

---

settings.yml

Pre-render members

---

landscape.yml

Add 'foundationproject' to Herald

---

landscape.yml

Ref https://github.com/lfph/lfph-landscape/pull/80#issuecomment-814256041

Add additional french repos

---

landscape.yml

change Herald github, Twitter

---

landscape.yml

move HI out of ENX

---

landscape.yml

Signed-off-by: Ry Jones <ry@linux.com>

Rakning uses GAEN as of today

---

netlify.toml

Signed-off-by: Jordi Noguera <jordinoguera83+github@gmail.com>

Fix functions not being deployed

---

landscape.yml

adding extra data into lfph landscape to prep for sync with lfph.io

---

landscape.yml

Signed-off-by: Jenny Wanger <jwanger@linuxfoundation.org>

update Kiel info

---

landscape.yml

Signed-off-by: Jenny Wanger <jwanger@linuxfoundation.org>

fixing WA state DOH

---

landscape.yml

Testing a description change to monitor effect on website
Signed-off-by: rs59 <97830491+rs59@users.noreply.github.com>

Change to Covid Green in yaml file
